### ISSUE TITLE
Minor css changes.

### ISSUE THREAD

**Issue by soundslikeinfo** [weph/obsidian-bookshelf#20]
I created a small css snippet to place in appearances so that the tiles look more rounded and less padded. I provided my css modifications, and a screenshot of how the books in the bookshelf appear after these subtle css updates.

_.obsidian/snippets/obsidian-bookshelf-mods.css_

```css
[class*="bookshelf--gallery-module--gallery"]{
    align-items: center;
}
[class*="bookshelf--gallery-card-module--galleryCard"]{
    padding: 5px;
    border-radius: 20px;
    height: fit-content;
}
```

![Image](https://github.com/user-attachments/assets/ba278d6f-8c28-4462-a984-9611da52e42b)

**Comment by weph** [comment]
Hey @soundslikeinfo 

Looks good! The only thing I'm not fully on board with is the border radius amount. I'm aiming for Bookshelf to feel like a natural extension of Obsidian. I think Obsidian roudness sits somewhere in between your version and the current rectangular look. I'll take a look at Obsidian's defaults and align it with that.

You'll still need an override if you prefer the extra-rounded look, but then it should be enough to just tweak the border-radius without touching the other properties. Hope that's a good compromise!

**Comment by weph** [comment]
Hey @soundslikeinfo 

this will be included in 0.13.0, which should be out in the next couple days.

The default is now a padding of 8 pixels, and a border radius of 6. To get the look you want, you can now tweak it easily using the available CSS variables:

```css
body {
    --bookshelf--gallery-card--padding: 5px;
    --bookshelf--gallery-card--border-radius: 20px;
}
```

In your screenshot, it looks like the cover images have rounded corners too, but it wasn't in your snippet. Just in case you want them rounded as well, there's a new variable for that:

```css
body {
    --bookshelf--gallery-card--image--border-radius: 20px;
}
```

There's also a new section in the documentation about styling Bookshelf. It'll go live with the new release, but you can already take a peek here: https://github.com/weph/obsidian-bookshelf/blob/main/docs/docs/styling.md
