### ISSUE TITLE
[Feature Request] Organize Books with Folder System

### ISSUE THREAD

**Issue by yijintutu** [weph/obsidian-bookshelf#6]
Implement a system to organize and categorize books by grouping similar book cards into folders on the bookshelf for streamlined navigation and management.

**Comment by weph** [comment]
Hey @yijintutu 

thanks for your suggestion! I've had a similar idea on my list: allowing books to be added to one or more shelves. This way, you could create shelves like 'Want to Read,' 'Favorites,' or 'Fantasy Classics.' On top of that, I'd include a filter to show only selected shelves and an option to display books grouped by shelf.

Would this approach work for what you have in mind?
If not, please give me some examples on how you're planning to use it.

**Comment by yijintutu** [comment]
Yes, allowing books to be added to one or multiple bookshelves (like a tagging system) is excellent. A book could be labeled with multiple tags, and users could determine groupings by filtering these tags. My idea is to extend the search functionality to:
Enable searching by both book titles and tags
Generate statistical data from tags to create an interactive slider/list , providing more intuitive and efficient filtering navigation.

**Comment by weph** [comment]
Hey @yijintutu 

I just released version 0.9.0, which includes the ability to add books to one or more lists. Lists are defined as a frontmatter property, and -  as with other properties -  you can configure the property name in the settings.

Here's example frontmatter block from a book in the demo vault. This book is on two lists: "Programming Books" and "Testing"

```yaml
cover: "[[test-driven-development-by-example.jpg]]"
author:
  - "[[Kent Beck]]"
published: 2002-01-01
tags:
  - computer-science
  - programming
  - tdd
rating: 5
pages: 216
lists:
  - "Programming Books"
  - "Testing"
```

To group books by their lists, just select "List" from the "Grouping" dropdown in the library view:

![Image](https://github.com/user-attachments/assets/17d475ec-e47f-407c-a818-2cc5bb902218)
